apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: NodePort
  ports:
    - name: https
      port: 9443
      targetPort: 9443
      nodePort: 30000
  selector:
    app: portainer