apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bootstrap
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/home-cluster/system"
  sourceRef:
    kind: GitRepository
    name: flux-system